// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/topology/v1/topology.proto

package topologypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeState int32

const (
	NodeState_NODE_STATE_UNSPECIFIED NodeState = 0
	NodeState_NODE_STATE_JOINING     NodeState = 1
	NodeState_NODE_STATE_READY       NodeState = 2
	NodeState_NODE_STATE_SUSPECT     NodeState = 3
	NodeState_NODE_STATE_UNREACHABLE NodeState = 4
	NodeState_NODE_STATE_DRAINING    NodeState = 5
	NodeState_NODE_STATE_LEAVING     NodeState = 6
	NodeState_NODE_STATE_REMOVED     NodeState = 7
)

// Enum value maps for NodeState.
var (
	NodeState_name = map[int32]string{
		0: "NODE_STATE_UNSPECIFIED",
		1: "NODE_STATE_JOINING",
		2: "NODE_STATE_READY",
		3: "NODE_STATE_SUSPECT",
		4: "NODE_STATE_UNREACHABLE",
		5: "NODE_STATE_DRAINING",
		6: "NODE_STATE_LEAVING",
		7: "NODE_STATE_REMOVED",
	}
	NodeState_value = map[string]int32{
		"NODE_STATE_UNSPECIFIED": 0,
		"NODE_STATE_JOINING":     1,
		"NODE_STATE_READY":       2,
		"NODE_STATE_SUSPECT":     3,
		"NODE_STATE_UNREACHABLE": 4,
		"NODE_STATE_DRAINING":    5,
		"NODE_STATE_LEAVING":     6,
		"NODE_STATE_REMOVED":     7,
	}
)

func (x NodeState) Enum() *NodeState {
	p := new(NodeState)
	*p = x
	return p
}

func (x NodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_topology_v1_topology_proto_enumTypes[0].Descriptor()
}

func (NodeState) Type() protoreflect.EnumType {
	return &file_api_topology_v1_topology_proto_enumTypes[0]
}

func (x NodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeState.Descriptor instead.
func (NodeState) EnumDescriptor() ([]byte, []int) {
	return file_api_topology_v1_topology_proto_rawDescGZIP(), []int{0}
}

type WatchdogRole int32

const (
	WatchdogRole_WATCHDOG_ROLE_UNSPECIFIED WatchdogRole = 0
	WatchdogRole_WATCHDOG_ROLE_PRIMARY     WatchdogRole = 1
	WatchdogRole_WATCHDOG_ROLE_STANDBY     WatchdogRole = 2
)

// Enum value maps for WatchdogRole.
var (
	WatchdogRole_name = map[int32]string{
		0: "WATCHDOG_ROLE_UNSPECIFIED",
		1: "WATCHDOG_ROLE_PRIMARY",
		2: "WATCHDOG_ROLE_STANDBY",
	}
	WatchdogRole_value = map[string]int32{
		"WATCHDOG_ROLE_UNSPECIFIED": 0,
		"WATCHDOG_ROLE_PRIMARY":     1,
		"WATCHDOG_ROLE_STANDBY":     2,
	}
)

func (x WatchdogRole) Enum() *WatchdogRole {
	p := new(WatchdogRole)
	*p = x
	return p
}

func (x WatchdogRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchdogRole) Descriptor() protoreflect.EnumDescriptor {
	return file_api_topology_v1_topology_proto_enumTypes[1].Descriptor()
}

func (WatchdogRole) Type() protoreflect.EnumType {
	return &file_api_topology_v1_topology_proto_enumTypes[1]
}

func (x WatchdogRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchdogRole.Descriptor instead.
func (WatchdogRole) EnumDescriptor() ([]byte, []int) {
	return file_api_topology_v1_topology_proto_rawDescGZIP(), []int{1}
}

type TopologyReason int32

const (
	TopologyReason_TOPOLOGY_REASON_UNSPECIFIED    TopologyReason = 0
	TopologyReason_TOPOLOGY_REASON_EVENT          TopologyReason = 1
	TopologyReason_TOPOLOGY_REASON_BOOKWORM       TopologyReason = 2
	TopologyReason_TOPOLOGY_REASON_PRUNE          TopologyReason = 3
	TopologyReason_TOPOLOGY_REASON_RECONCILE      TopologyReason = 4
	TopologyReason_TOPOLOGY_REASON_PRIMARY_CHANGE TopologyReason = 5
)

// Enum value maps for TopologyReason.
var (
	TopologyReason_name = map[int32]string{
		0: "TOPOLOGY_REASON_UNSPECIFIED",
		1: "TOPOLOGY_REASON_EVENT",
		2: "TOPOLOGY_REASON_BOOKWORM",
		3: "TOPOLOGY_REASON_PRUNE",
		4: "TOPOLOGY_REASON_RECONCILE",
		5: "TOPOLOGY_REASON_PRIMARY_CHANGE",
	}
	TopologyReason_value = map[string]int32{
		"TOPOLOGY_REASON_UNSPECIFIED":    0,
		"TOPOLOGY_REASON_EVENT":          1,
		"TOPOLOGY_REASON_BOOKWORM":       2,
		"TOPOLOGY_REASON_PRUNE":          3,
		"TOPOLOGY_REASON_RECONCILE":      4,
		"TOPOLOGY_REASON_PRIMARY_CHANGE": 5,
	}
)

func (x TopologyReason) Enum() *TopologyReason {
	p := new(TopologyReason)
	*p = x
	return p
}

func (x TopologyReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopologyReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_topology_v1_topology_proto_enumTypes[2].Descriptor()
}

func (TopologyReason) Type() protoreflect.EnumType {
	return &file_api_topology_v1_topology_proto_enumTypes[2]
}

func (x TopologyReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopologyReason.Descriptor instead.
func (TopologyReason) EnumDescriptor() ([]byte, []int) {
	return file_api_topology_v1_topology_proto_rawDescGZIP(), []int{2}
}

type TopologyQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StackId       string                 `protobuf:"bytes,1,opt,name=stack_id,json=stackId,proto3" json:"stack_id,omitempty"`
	ObservedEpoch int64                  `protobuf:"varint,2,opt,name=observed_epoch,json=observedEpoch,proto3" json:"observed_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyQuery) Reset() {
	*x = TopologyQuery{}
	mi := &file_api_topology_v1_topology_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyQuery) ProtoMessage() {}

func (x *TopologyQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_topology_v1_topology_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyQuery.ProtoReflect.Descriptor instead.
func (*TopologyQuery) Descriptor() ([]byte, []int) {
	return file_api_topology_v1_topology_proto_rawDescGZIP(), []int{0}
}

func (x *TopologyQuery) GetStackId() string {
	if x != nil {
		return x.StackId
	}
	return ""
}

func (x *TopologyQuery) GetObservedEpoch() int64 {
	if x != nil {
		return x.ObservedEpoch
	}
	return 0
}

type Heartbeat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StackId         string                 `protobuf:"bytes,1,opt,name=stack_id,json=stackId,proto3" json:"stack_id,omitempty"`
	NodeId          string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PodName         string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodIp           string                 `protobuf:"bytes,4,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	Incarnation     int64                  `protobuf:"varint,5,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	ObservedEpoch   int64                  `protobuf:"varint,6,opt,name=observed_epoch,json=observedEpoch,proto3" json:"observed_epoch,omitempty"`
	State           NodeState              `protobuf:"varint,7,opt,name=state,proto3,enum=topology.v1.NodeState" json:"state,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,8,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_topology_v1_topology_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_topology_v1_topology_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_topology_v1_topology_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetStackId() string {
	if x != nil {
		return x.StackId
	}
	return ""
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Heartbeat) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *Heartbeat) GetIncarnation() int64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *Heartbeat) GetObservedEpoch() int64 {
	if x != nil {
		return x.ObservedEpoch
	}
	return 0
}

func (x *Heartbeat) GetState() NodeState {
	if x != nil {
		return x.State
	}
	return NodeState_NODE_STATE_UNSPECIFIED
}

func (x *Heartbeat) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type Member struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PodName        string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodIp          string                 `protobuf:"bytes,3,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	Incarnation    int64                  `protobuf:"varint,4,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	State          NodeState              `protobuf:"varint,5,opt,name=state,proto3,enum=topology.v1.NodeState" json:"state,omitempty"`
	LastSeenUnixMs int64                  `protobuf:"varint,6,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_api_topology_v1_topology_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_api_topology_v1_topology_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_api_topology_v1_topology_proto_rawDescGZIP(), []int{2}
}

func (x *Member) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Member) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Member) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *Member) GetIncarnation() int64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *Member) GetState() NodeState {
	if x != nil {
		return x.State
	}
	return NodeState_NODE_STATE_UNSPECIFIED
}

func (x *Member) GetLastSeenUnixMs() int64 {
	if x != nil {
		return x.LastSeenUnixMs
	}
	return 0
}

type TopologyEnvelope struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StackId            string                 `protobuf:"bytes,1,opt,name=stack_id,json=stackId,proto3" json:"stack_id,omitempty"`
	Members            []*Member              `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Epoch              int64                  `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Reason             TopologyReason         `protobuf:"varint,4,opt,name=reason,proto3,enum=topology.v1.TopologyReason" json:"reason,omitempty"`
	ValidUntilUnixMs   int64                  `protobuf:"varint,5,opt,name=valid_until_unix_ms,json=validUntilUnixMs,proto3" json:"valid_until_unix_ms,omitempty"`
	WatchdogId         string                 `protobuf:"bytes,6,opt,name=watchdog_id,json=watchdogId,proto3" json:"watchdog_id,omitempty"`
	WatchdogGeneration int64                  `protobuf:"varint,7,opt,name=watchdog_generation,json=watchdogGeneration,proto3" json:"watchdog_generation,omitempty"`
	WatchdogRole       WatchdogRole           `protobuf:"varint,8,opt,name=watchdog_role,json=watchdogRole,proto3,enum=topology.v1.WatchdogRole" json:"watchdog_role,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TopologyEnvelope) Reset() {
	*x = TopologyEnvelope{}
	mi := &file_api_topology_v1_topology_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyEnvelope) ProtoMessage() {}

func (x *TopologyEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_topology_v1_topology_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyEnvelope.ProtoReflect.Descriptor instead.
func (*TopologyEnvelope) Descriptor() ([]byte, []int) {
	return file_api_topology_v1_topology_proto_rawDescGZIP(), []int{3}
}

func (x *TopologyEnvelope) GetStackId() string {
	if x != nil {
		return x.StackId
	}
	return ""
}

func (x *TopologyEnvelope) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *TopologyEnvelope) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TopologyEnvelope) GetReason() TopologyReason {
	if x != nil {
		return x.Reason
	}
	return TopologyReason_TOPOLOGY_REASON_UNSPECIFIED
}

func (x *TopologyEnvelope) GetValidUntilUnixMs() int64 {
	if x != nil {
		return x.ValidUntilUnixMs
	}
	return 0
}

func (x *TopologyEnvelope) GetWatchdogId() string {
	if x != nil {
		return x.WatchdogId
	}
	return ""
}

func (x *TopologyEnvelope) GetWatchdogGeneration() int64 {
	if x != nil {
		return x.WatchdogGeneration
	}
	return 0
}

func (x *TopologyEnvelope) GetWatchdogRole() WatchdogRole {
	if x != nil {
		return x.WatchdogRole
	}
	return WatchdogRole_WATCHDOG_ROLE_UNSPECIFIED
}

var File_api_topology_v1_topology_proto protoreflect.FileDescriptor

const file_api_topology_v1_topology_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/topology/v1/topology.proto\x12\vtopology.v1\"Q\n" +
	"\rTopologyQuery\x12\x19\n" +
	"\bstack_id\x18\x01 \x01(\tR\astackId\x12%\n" +
	"\x0eobserved_epoch\x18\x02 \x01(\x03R\robservedEpoch\"\x93\x02\n" +
	"\tHeartbeat\x12\x19\n" +
	"\bstack_id\x18\x01 \x01(\tR\astackId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12\x15\n" +
	"\x06pod_ip\x18\x04 \x01(\tR\x05podIp\x12 \n" +
	"\vincarnation\x18\x05 \x01(\x03R\vincarnation\x12%\n" +
	"\x0eobserved_epoch\x18\x06 \x01(\x03R\robservedEpoch\x12,\n" +
	"\x05state\x18\a \x01(\x0e2\x16.topology.v1.NodeStateR\x05state\x12)\n" +
	"\x10protocol_version\x18\b \x01(\tR\x0fprotocolVersion\"\xce\x01\n" +
	"\x06Member\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x15\n" +
	"\x06pod_ip\x18\x03 \x01(\tR\x05podIp\x12 \n" +
	"\vincarnation\x18\x04 \x01(\x03R\vincarnation\x12,\n" +
	"\x05state\x18\x05 \x01(\x0e2\x16.topology.v1.NodeStateR\x05state\x12)\n" +
	"\x11last_seen_unix_ms\x18\x06 \x01(\x03R\x0elastSeenUnixMs\"\xe8\x02\n" +
	"\x10TopologyEnvelope\x12\x19\n" +
	"\bstack_id\x18\x01 \x01(\tR\astackId\x12-\n" +
	"\amembers\x18\x02 \x03(\v2\x13.topology.v1.MemberR\amembers\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x03R\x05epoch\x123\n" +
	"\x06reason\x18\x04 \x01(\x0e2\x1b.topology.v1.TopologyReasonR\x06reason\x12-\n" +
	"\x13valid_until_unix_ms\x18\x05 \x01(\x03R\x10validUntilUnixMs\x12\x1f\n" +
	"\vwatchdog_id\x18\x06 \x01(\tR\n" +
	"watchdogId\x12/\n" +
	"\x13watchdog_generation\x18\a \x01(\x03R\x12watchdogGeneration\x12>\n" +
	"\rwatchdog_role\x18\b \x01(\x0e2\x19.topology.v1.WatchdogRoleR\fwatchdogRole*\xd2\x01\n" +
	"\tNodeState\x12\x1a\n" +
	"\x16NODE_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NODE_STATE_JOINING\x10\x01\x12\x14\n" +
	"\x10NODE_STATE_READY\x10\x02\x12\x16\n" +
	"\x12NODE_STATE_SUSPECT\x10\x03\x12\x1a\n" +
	"\x16NODE_STATE_UNREACHABLE\x10\x04\x12\x17\n" +
	"\x13NODE_STATE_DRAINING\x10\x05\x12\x16\n" +
	"\x12NODE_STATE_LEAVING\x10\x06\x12\x16\n" +
	"\x12NODE_STATE_REMOVED\x10\a*c\n" +
	"\fWatchdogRole\x12\x1d\n" +
	"\x19WATCHDOG_ROLE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15WATCHDOG_ROLE_PRIMARY\x10\x01\x12\x19\n" +
	"\x15WATCHDOG_ROLE_STANDBY\x10\x02*\xc8\x01\n" +
	"\x0eTopologyReason\x12\x1f\n" +
	"\x1bTOPOLOGY_REASON_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TOPOLOGY_REASON_EVENT\x10\x01\x12\x1c\n" +
	"\x18TOPOLOGY_REASON_BOOKWORM\x10\x02\x12\x19\n" +
	"\x15TOPOLOGY_REASON_PRUNE\x10\x03\x12\x1d\n" +
	"\x19TOPOLOGY_REASON_RECONCILE\x10\x04\x12\"\n" +
	"\x1eTOPOLOGY_REASON_PRIMARY_CHANGE\x10\x052\x9f\x01\n" +
	"\x0fTopologyControl\x12H\n" +
	"\vGetTopology\x12\x1a.topology.v1.TopologyQuery\x1a\x1d.topology.v1.TopologyEnvelope\x12B\n" +
	"\x05Watch\x12\x16.topology.v1.Heartbeat\x1a\x1d.topology.v1.TopologyEnvelope(\x010\x01B=Z;github.com/zhixiongdu/olricstack/api/topology/v1;topologypbb\x06proto3"

var (
	file_api_topology_v1_topology_proto_rawDescOnce sync.Once
	file_api_topology_v1_topology_proto_rawDescData []byte
)

func file_api_topology_v1_topology_proto_rawDescGZIP() []byte {
	file_api_topology_v1_topology_proto_rawDescOnce.Do(func() {
		file_api_topology_v1_topology_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_topology_v1_topology_proto_rawDesc), len(file_api_topology_v1_topology_proto_rawDesc)))
	})
	return file_api_topology_v1_topology_proto_rawDescData
}

var file_api_topology_v1_topology_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_topology_v1_topology_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_topology_v1_topology_proto_goTypes = []any{
	(NodeState)(0),           // 0: topology.v1.NodeState
	(WatchdogRole)(0),        // 1: topology.v1.WatchdogRole
	(TopologyReason)(0),      // 2: topology.v1.TopologyReason
	(*TopologyQuery)(nil),    // 3: topology.v1.TopologyQuery
	(*Heartbeat)(nil),        // 4: topology.v1.Heartbeat
	(*Member)(nil),           // 5: topology.v1.Member
	(*TopologyEnvelope)(nil), // 6: topology.v1.TopologyEnvelope
}
var file_api_topology_v1_topology_proto_depIdxs = []int32{
	0, // 0: topology.v1.Heartbeat.state:type_name -> topology.v1.NodeState
	0, // 1: topology.v1.Member.state:type_name -> topology.v1.NodeState
	5, // 2: topology.v1.TopologyEnvelope.members:type_name -> topology.v1.Member
	2, // 3: topology.v1.TopologyEnvelope.reason:type_name -> topology.v1.TopologyReason
	1, // 4: topology.v1.TopologyEnvelope.watchdog_role:type_name -> topology.v1.WatchdogRole
	3, // 5: topology.v1.TopologyControl.GetTopology:input_type -> topology.v1.TopologyQuery
	4, // 6: topology.v1.TopologyControl.Watch:input_type -> topology.v1.Heartbeat
	6, // 7: topology.v1.TopologyControl.GetTopology:output_type -> topology.v1.TopologyEnvelope
	6, // 8: topology.v1.TopologyControl.Watch:output_type -> topology.v1.TopologyEnvelope
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_topology_v1_topology_proto_init() }
func file_api_topology_v1_topology_proto_init() {
	if File_api_topology_v1_topology_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_topology_v1_topology_proto_rawDesc), len(file_api_topology_v1_topology_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_topology_v1_topology_proto_goTypes,
		DependencyIndexes: file_api_topology_v1_topology_proto_depIdxs,
		EnumInfos:         file_api_topology_v1_topology_proto_enumTypes,
		MessageInfos:      file_api_topology_v1_topology_proto_msgTypes,
	}.Build()
	File_api_topology_v1_topology_proto = out.File
	file_api_topology_v1_topology_proto_goTypes = nil
	file_api_topology_v1_topology_proto_depIdxs = nil
}
