// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/topology/v1/topology.proto

package topologypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TopologyControl_GetTopology_FullMethodName = "/topology.v1.TopologyControl/GetTopology"
	TopologyControl_Watch_FullMethodName       = "/topology.v1.TopologyControl/Watch"
)

// TopologyControlClient is the client API for TopologyControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TopologyControlClient interface {
	GetTopology(ctx context.Context, in *TopologyQuery, opts ...grpc.CallOption) (*TopologyEnvelope, error)
	Watch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Heartbeat, TopologyEnvelope], error)
}

type topologyControlClient struct {
	cc grpc.ClientConnInterface
}

func NewTopologyControlClient(cc grpc.ClientConnInterface) TopologyControlClient {
	return &topologyControlClient{cc}
}

func (c *topologyControlClient) GetTopology(ctx context.Context, in *TopologyQuery, opts ...grpc.CallOption) (*TopologyEnvelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopologyEnvelope)
	err := c.cc.Invoke(ctx, TopologyControl_GetTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyControlClient) Watch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Heartbeat, TopologyEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TopologyControl_ServiceDesc.Streams[0], TopologyControl_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Heartbeat, TopologyEnvelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopologyControl_WatchClient = grpc.BidiStreamingClient[Heartbeat, TopologyEnvelope]

// TopologyControlServer is the server API for TopologyControl service.
// All implementations must embed UnimplementedTopologyControlServer
// for forward compatibility.
type TopologyControlServer interface {
	GetTopology(context.Context, *TopologyQuery) (*TopologyEnvelope, error)
	Watch(grpc.BidiStreamingServer[Heartbeat, TopologyEnvelope]) error
	mustEmbedUnimplementedTopologyControlServer()
}

// UnimplementedTopologyControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTopologyControlServer struct{}

func (UnimplementedTopologyControlServer) GetTopology(context.Context, *TopologyQuery) (*TopologyEnvelope, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopology not implemented")
}
func (UnimplementedTopologyControlServer) Watch(grpc.BidiStreamingServer[Heartbeat, TopologyEnvelope]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedTopologyControlServer) mustEmbedUnimplementedTopologyControlServer() {}
func (UnimplementedTopologyControlServer) testEmbeddedByValue()                         {}

// UnsafeTopologyControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TopologyControlServer will
// result in compilation errors.
type UnsafeTopologyControlServer interface {
	mustEmbedUnimplementedTopologyControlServer()
}

func RegisterTopologyControlServer(s grpc.ServiceRegistrar, srv TopologyControlServer) {
	// If the following call panics, it indicates UnimplementedTopologyControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TopologyControl_ServiceDesc, srv)
}

func _TopologyControl_GetTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopologyQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyControlServer).GetTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyControl_GetTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyControlServer).GetTopology(ctx, req.(*TopologyQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyControl_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TopologyControlServer).Watch(&grpc.GenericServerStream[Heartbeat, TopologyEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopologyControl_WatchServer = grpc.BidiStreamingServer[Heartbeat, TopologyEnvelope]

// TopologyControl_ServiceDesc is the grpc.ServiceDesc for TopologyControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TopologyControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "topology.v1.TopologyControl",
	HandlerType: (*TopologyControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTopology",
			Handler:    _TopologyControl_GetTopology_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _TopologyControl_Watch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/topology/v1/topology.proto",
}
